server:
  port: 8081

zest:
  llm:
    enabled: true
    control-plane-url: http://127.0.0.1:8088
    app-key: order-service
    auth-token: demo-token-123
    registry-on-startup: true
  flow:
    executor:
      port: 20551

spring:
  application:
    name: zest-llm-demo
