{{- if not .Values.mysql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zest-llm.fullname" . }}-mysql
  labels:
    app.kubernetes.io/name: {{ include "zest-llm.name" . }}
type: Opaque
stringData:
  password: {{ .Values.mysql.password | quote }}
{{- end }}
