apiVersion: v1
kind: Service
metadata:
  name: {{ include "zest-llm.fullname" . }}-demo
  labels:
    app.kubernetes.io/name: {{ include "zest-llm.name" . }}
    app.kubernetes.io/component: demo
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.demo.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "zest-llm.name" . }}
    app.kubernetes.io/component: demo
