apiVersion: v1
kind: Service
metadata:
  name: {{ include "zest-llm.fullname" . }}-admin
  labels:
    app.kubernetes.io/name: {{ include "zest-llm.name" . }}
    app.kubernetes.io/component: admin
spec:
  type: {{ .Values.service.admin.type }}
  ports:
    - port: {{ .Values.service.admin.port }}
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "zest-llm.name" . }}
    app.kubernetes.io/component: admin
